version: '3'

services:
  prod:
    image: tons/event-rooster-web
    build: .
    ports:
      - 8081:8080

  dev:
    image: node:alpine
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'npm install && exec npm run dev'
    ports:
      - 80:80
    stdin_open: true
    tty: true
    environment:
      ONELINERS_API: ${BACKEND}
      HOST: 0.0.0.0
      PORT: 80
      CHOKIDAR_USEPOLLING: "true"

