version: '3'

services:
  prod:
    image: tons/event-rooster-web
    build: .
    ports:
      - 8081:8080

  dev:
    image: node:15.13.0-alpine3.13
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'yarn install && exec yarn serve'
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
