version: '3'

services:
  prod:
    image: tons/event-rooster-web
    build: .
    ports:
      - 8080:8080

  dev:
    build:
      context: .
      target: builder
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'yarn install && exec yarn serve --mode local'
    ports:
      - 8081:8080
    tty: true
