environments:
  dev:
    values:
      - kubeContext: nuc
      - name: event-rooster-web
      - hostname: event-rooster.dev.fitfit.dk
      - certIssuer: letsencrypt-staging
      - replicaCount: 1

  prod:
    values:
      - kubeContext: nuc
      - name: event-rooster-web
      - hostname: event-rooster.fitfit.dk
      - certIssuer: letsencrypt-prod
      - replicaCount: 2

  feature:
    values:
      - kubeContext: nuc
      - name: event-rooster-web{{ .Environment.Name }}-{{ requiredEnv "FEATURE_TAG" }}
      - hostname: event-rooster-{{ requiredEnv "FEATURE_TAG" }}.fitfit.dk
      - certIssuer: letsencrypt-staging
      - replicaCount: 1

releases:
  - name: "{{ .Values.name }}"
    namespace: event-rooster-{{ .Environment.Name }}
    chart: helm/
    kubeContext: "{{ .Values.kubeContext }}"
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.hostname }}
          certIssuer: {{ .Values.certIssuer }}
      - replicaCount: {{ .Values.replicaCount }}

helmDefaults:
  recreatePods: true
